### ISSUE TITLE
Separate Game and Engine logic?

### ISSUE THREAD

**Issue by guilhermepo2** [guilhermepo2/realiti2D#12]
Currently, `Application.cpp`  initializes SDL, the Renderer, Input System, Entity Manager, Collision World. It processes input for ImGUI, InputSystem, the Application itself and the Entity Manager. It Updates the EntityManager and the Collision World. It renders the Entity Manager, the Collision World (if applicable) and signalize the Renderer to draw the scene.

**Problem:**  The `Application` should be a generic graphical/interactive framework, it should not be aware of game-specific functionality. It gets obvious when trying to make an Editor or any tools using the Application, why does a Level Editor would have a Collision World? an Entity Manager?

**Possible Solution(s):**
The first possible solution is to add the concept of **Layers** into the engine, this way the Application initializes SDL, and the Renderer. After that, it do its own things, sure, but Processing Input is mostly *"Hey layers, update your inputs!"* instead of *"Hey InputSystem, it's time for you to update, now I  update, now it's your turn ImGui, now you go Entities..."* 

This open the idea of having many different layers, such as:
1. Game Layer (Pushes the layers of Game Input System, Entity Manager, and Collision World (UI in the Future))
2. Tools Layer (Won't have game-related stuff)
3. Debug Layer (Debug Collision World, Debug ImGUI, etc...)

**Comment by brianbatista93** [comment]
I think you should split the "initializations" by functionality. i.e InitializePlatformSpecifics, InitializeGraphics, InitializeGameLogics.
This way you can decide what and when the subsystems will be initialized.
For example: If you have an editor you can choose what to initialize and so on.

**Comment by guilhermepo2** [comment]
Hmmmmmmmmmmmmmmmmmmmmmm
